# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C0TTU4MXxGfrI7RoqhH8XhApJsQ6-xx7
"""

!pip install ctgan

import pandas as pd

raw_data = pd.read_csv('/content/Chto-to_fixed.csv', sep=None, encoding='latin-1',engine='python')
raw_data.info()

raw_df = raw_data.copy()
raw_df.info()

raw_df.fillna(0)

raw_df.transpose()

train_df = raw_df.select_dtypes(exclude="object")

train_df.info()

# Выбираем столбцы с типом object
object_cols = raw_df.select_dtypes(exclude='float').columns.to_list()

# Заменяем ячейки на 0
for i in object_cols:
    raw_df[i] = raw_df[i].fillna(0)

# Выводим результат
object_cols

raw_df = raw_df.astype(str)

train_df

raw_df.info()

"""#Нейросеть

1.   Новый пункт

1.   Новый пункт
2.   Новый пункт


2.   Новый пункт




"""

from ctgan import CTGAN

ctgan = CTGAN(epochs=1)

ctgan.fit(train_df)

ctgan.save('my_model.pkl') #скачивание матрицы весов
load = CTGAN.load('my_model.pkl') #подгрузка матрицы
model = CTGAN(load)
model = load.sample(num_rows=200) #генерация 300 сэмплов (300 строк с данными). ЧИСЛО ГЕНЕРАЦИЙ СТАВИТЬ КРАТНЫМ 3!!!

from sdv.evaluation.single_table import evaluate_quality

quality_report = evaluate_quality(
    real_data=real_data,
    synthetic_data=synthetic_data,
    metadata=metadata)